FROM python:3.10-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN pip install --no-cache-dir \
    pyspark \
    pyyaml \
    pandas \
    pyarrow

COPY batch/ /app/batch/
COPY config/ /app/config/

ENV PYTHONPATH=/app

CMD ["python", "-m", "batch.etl_senamhi"]
